apiVersion: extensions/v1beta1 # this apiVersion is expired but this is the only one working
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # rewriting target
spec:
  rules:
    - http:
        paths:
          - path: /?(.*) # this must be in same format -- simple route
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*) # this must be in same format -- here /api will be removed from the route as we did with nginx in docker
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
